### PR TITLE
added fastlane metadata

### PR DESCRIPTION
**Pull request by robinpaulson**
Added fastlane metadata, necessary for f-droid repo

### CODE REVIEW

**Comment by robinpaulson** [comment]
Before you accept this: One of the files, make sure the latest file in the "changelogs" subdir matches the versionCode of the latest release. At the moment, the latest file is "198", which matched the **last** release you made. They need to be in sync.

Whenever you do a release, it will require a new file adding to that "changelog" dir. I use the same text i put in the Github release info.

Please ask if this isn't clear.

**Comment by freshollie** [comment]
This all makes sense, thanks @robinpaulson !

> Before you accept this: ...

I assume this doesn't mean I have to do anything now right? I'm fine for creating change logs on releases :)

**Comment by robinpaulson** [comment]
You could do a new release now, if it was me I'd be tempted to, to make sure the fastlane stuff and the git tagging is all working in sync.

It looks like you have a long release cycle anyway, so doing this would make sure there was at least one version available in F-Droid.

Or ask me to make the next release if you prefer, I can make a PR.

**Comment by freshollie** [comment]
@robinpaulson any chance you are ok with removing all the screenshots from the `screenshots` directory and instead referring the readme to the `fastlane` directory instead?

**Comment by robinpaulson** [comment]
> @robinpaulson any chance you are ok with removing all the screenshots from the `screenshots`
> directory

yes, can do

> instead referring the readme to the `fastlane` directory instead?

ah, you mean linking them into readme.md from the fastlane dir? yes, i can do that too. that's a good idea, of course i should have done that earlier. double-ups!

**Comment by robinpaulson** [comment]
Done

**Comment by freshollie** [comment]
Thanks for the work!

**Pull request merged**
